on:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review]
    paths:
      - proposals/N3GOV-*.json
name: PR for governance proposal
jobs:
  validate_configurations:
    name: Validate governance proposal against the spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: proposals/N3GOV-*.json
      - name: Validate against JSON schema
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: cardinalby/schema-validator-action@v1
        with:
          file: ${{ steps.changed-files.outputs.all_changed_files }}
          schema: 'https://raw.githubusercontent.com/nation3/gov/main/specs/N3GOV-v2.json'
